const express=require('express');
const {asyncHandler}=require('../utils/async-handler');
const {requireAuth}=require('../middleware/auth.middleware');
const {requireOwner}=require('../middleware/role.middleware');
const page=require('../controllers/page.controller');
const api=require('../controllers/api.controller');
const {upload}=require('../middleware/upload.middleware');
const {validate}=require('../middleware/validation.middleware');
const {z}=require('zod');
const {loadEnv}=require('../config/env');

const pageRouter=express.Router();
pageRouter.get('/',asyncHandler(page.home));
pageRouter.get('/store',asyncHandler(page.store));
pageRouter.get('/product/:slug',asyncHandler(page.productDetail));
pageRouter.get('/search',asyncHandler(page.search));
pageRouter.get('/services',asyncHandler(page.servicesPage));
pageRouter.get('/faq',asyncHandler(page.faq));
pageRouter.get('/security',asyncHandler(page.security)); pageRouter.get('/privacy',asyncHandler(page.legal)); pageRouter.get('/terms',asyncHandler(page.legal)); pageRouter.get('/refund',asyncHandler(page.legal));
pageRouter.get('/auth/login',asyncHandler(page.login));
pageRouter.get('/auth/register',asyncHandler(page.register));
pageRouter.get('/auth/forgot-password',asyncHandler(page.forgotPassword));
pageRouter.get('/auth/reset-password',asyncHandler(page.resetPassword));
pageRouter.get('/auth/callback',asyncHandler(page.authCallback));
pageRouter.get('/dashboard',requireAuth,asyncHandler(page.dashboard));
pageRouter.get('/cart',requireAuth,asyncHandler(page.cartPage));
pageRouter.get('/checkout',requireAuth,asyncHandler(page.checkout));
pageRouter.get('/orders',requireAuth,asyncHandler(page.orders));
pageRouter.get('/orders/:id',requireAuth,asyncHandler(page.orderDetail));
pageRouter.get('/history',requireAuth,asyncHandler(page.history));
pageRouter.get('/deposit',requireAuth,asyncHandler(page.deposit));
pageRouter.get('/profile',requireAuth,asyncHandler(page.profilePage));
pageRouter.get('/messages',requireAuth,asyncHandler(page.messagesPage));
pageRouter.get('/messages/:id',requireAuth,asyncHandler(page.messageDetail));
pageRouter.get('/tickets',requireAuth,asyncHandler(page.ticketsPage));
pageRouter.get('/tickets/:id',requireAuth,asyncHandler(page.ticketDetail));
pageRouter.get('/notifications',requireAuth,asyncHandler(page.notificationsPage));
pageRouter.get('/top-order',asyncHandler(page.topOrder));
pageRouter.get('/payment/:id',requireAuth,asyncHandler(page.paymentStatus));
pageRouter.get('/delivery',requireAuth,asyncHandler(page.delivery));

const owner=express.Router(); owner.use(requireAuth,requireOwner);
const ownerSections=['dashboard','products','categories','orders','payments','deposits','users','tickets','activity','services','settings','maintenance','notifications','reports','security','faq','information','refunds'];
for(const s of ownerSections){ owner.get('/'+s,asyncHandler(page.ownerPage(s))); }
owner.get('/products/create',(req,res)=>res.redirect('/owner/products?create=1'));
owner.get('/',asyncHandler(page.ownerPage('dashboard')));
pageRouter.use('/owner',owner);

const apiRouter=express.Router();
apiRouter.get('/me',requireAuth,asyncHandler(api.authController.me));
apiRouter.post('/auth/register',validate(z.object({email:z.string().email(),password:z.string().min(8),username:z.string().min(3).max(32).regex(/^[a-zA-Z0-9._-]+$/)})),asyncHandler(api.authController.register));
apiRouter.post('/auth/login',validate(z.object({email:z.string().email(),password:z.string().min(8)})),asyncHandler(api.authController.login));
apiRouter.post('/auth/logout',requireAuth,asyncHandler(api.authController.logout));
apiRouter.post('/auth/forgot-password',validate(z.object({email:z.string().email()})),asyncHandler(api.authController.resetRequest));
apiRouter.post('/auth/reset-password',requireAuth,validate(z.object({password:z.string().min(8)})),asyncHandler(api.authController.resetPassword));
apiRouter.get('/auth/callback',asyncHandler(api.authController.callback));
apiRouter.get('/products',asyncHandler(api.productController.list));
apiRouter.get('/products/:slug',asyncHandler(api.productController.detail));
apiRouter.get('/categories',asyncHandler(api.productController.categories));
apiRouter.post('/cart',requireAuth,validate(z.object({productId:z.string().uuid(),quantity:z.coerce.number().int().min(1).max(100)})),asyncHandler(api.cartController.add));
apiRouter.get('/cart',requireAuth,asyncHandler(api.cartController.get));
apiRouter.put('/cart/:id',requireAuth,validate(z.object({quantity:z.coerce.number().int().min(1).max(100)})),asyncHandler(api.cartController.update));
apiRouter.delete('/cart/:id',requireAuth,asyncHandler(api.cartController.remove));
apiRouter.delete('/cart',requireAuth,asyncHandler(api.cartController.clear));
apiRouter.get('/checkout/preview',requireAuth,asyncHandler(api.orderController.preview));
apiRouter.post('/orders',requireAuth,validate(z.object({paymentMethod:z.enum(['BALANCE','GATEWAY']),idempotencyKey:z.string().min(8).max(100).optional(),returnUrl:z.string().url().optional()})),asyncHandler(api.orderController.create));
apiRouter.get('/orders',requireAuth,asyncHandler(api.orderController.list));
apiRouter.get('/orders/:id',requireAuth,asyncHandler(api.orderController.detail));
apiRouter.post('/payment/create',requireAuth,validate(z.object({orderId:z.string().uuid(),returnUrl:z.string().url().optional()})),asyncHandler(api.paymentController.create));
apiRouter.get('/payment/:id',requireAuth,asyncHandler(api.paymentController.status));
apiRouter.post('/deposit',requireAuth,validate(z.object({amount:z.coerce.number().int().min(1000),idempotencyKey:z.string().min(8).max(100).optional(),returnUrl:z.string().url().optional()})),asyncHandler(api.depositController.create));
apiRouter.get('/deposit',requireAuth,asyncHandler(api.depositController.list));
apiRouter.get('/balance',requireAuth,asyncHandler(api.depositController.wallet));
apiRouter.get('/balance/mutations',requireAuth,asyncHandler(api.depositController.mutations));
apiRouter.get('/download/:contentId',requireAuth,asyncHandler(api.deliveryController.access));
apiRouter.get('/profile',requireAuth,asyncHandler(api.profileController.get));
apiRouter.put('/profile',requireAuth,validate(z.object({username:z.string().min(3).max(32).optional(),display_name:z.string().max(80).optional(),phone:z.string().max(30).optional(),bio:z.string().max(500).optional()})),asyncHandler(api.profileController.update));
apiRouter.get('/profile/login-history',requireAuth,asyncHandler(api.profileController.history));
apiRouter.get('/messages',requireAuth,asyncHandler(api.messageController.list));
apiRouter.post('/messages',requireAuth,validate(z.object({body:z.string().min(1).max(10000)})),asyncHandler(api.messageController.create));
apiRouter.get('/messages/:id',requireAuth,asyncHandler(api.messageController.detail));
apiRouter.get('/tickets',requireAuth,asyncHandler(api.ticketController.list));
apiRouter.post('/tickets',requireAuth,validate(z.object({category:z.string().min(2).max(40),subject:z.string().min(3).max(120),priority:z.enum(['LOW','NORMAL','HIGH','URGENT']).optional(),message:z.string().min(2).max(10000)})),asyncHandler(api.ticketController.create));
apiRouter.get('/tickets/:id',requireAuth,asyncHandler(api.ticketController.detail));
apiRouter.post('/tickets/:id/messages',requireAuth,validate(z.object({body:z.string().min(1).max(10000)})),asyncHandler(api.ticketController.reply));
apiRouter.post('/tickets/:id/status',requireAuth,validate(z.object({status:z.enum(['OPEN','WAITING','REPLIED','CLOSED'])})),asyncHandler(api.ticketController.status));
apiRouter.get('/notifications',requireAuth,asyncHandler(api.notificationController.list));
apiRouter.get('/notifications/unread',requireAuth,asyncHandler(api.notificationController.unread));
apiRouter.put('/notifications/:id/read',requireAuth,asyncHandler(api.notificationController.read));
apiRouter.get('/services',asyncHandler(api.serviceController.list));
apiRouter.post('/service-orders',requireAuth,validate(z.object({serviceId:z.string().uuid(),requestData:z.record(z.any()).default({})})),asyncHandler(api.serviceController.order));
apiRouter.get('/faq',asyncHandler(api.contentController.faq));
apiRouter.get('/information',asyncHandler(api.contentController.information));
apiRouter.get('/search',asyncHandler(api.contentController.search));

const ownerApi=express.Router(); ownerApi.use(requireAuth,requireOwner);
ownerApi.get('/dashboard',asyncHandler(api.ownerController.dashboard));
ownerApi.get('/analytics',asyncHandler(api.ownerController.analytics));
ownerApi.get('/top-orders',asyncHandler(api.ownerController.topOrders));
ownerApi.get('/products',asyncHandler(api.ownerController.products));
ownerApi.post('/products',validate(z.object({name:z.string().min(2),slug:z.string().optional(),category_id:z.string().uuid().nullable().optional(),description:z.string().optional(),price:z.coerce.number().int().min(0),stock:z.coerce.number().int().min(0),status:z.enum(['DRAFT','PUBLISHED','ARCHIVED']).optional()})),asyncHandler(api.ownerController.productCreate));
ownerApi.put('/products/:id',validate(z.object({name:z.string().min(2).optional(),slug:z.string().optional(),category_id:z.string().uuid().nullable().optional(),description:z.string().optional(),price:z.coerce.number().int().min(0).optional(),stock:z.coerce.number().int().min(0).optional(),status:z.enum(['DRAFT','PUBLISHED','ARCHIVED']).optional(),thumbnail_path:z.string().optional()})),asyncHandler(api.ownerController.productUpdate));
ownerApi.post('/products/:id/publish',asyncHandler(api.ownerController.productPublish));
ownerApi.post('/products/:id/unpublish',asyncHandler(api.ownerController.productUnpublish));
ownerApi.post('/products/:id/archive',asyncHandler(api.ownerController.productArchive));
ownerApi.post('/products/:id/duplicate',asyncHandler(api.ownerController.productDuplicate));
ownerApi.delete('/products/:id/delete',asyncHandler(api.ownerController.productDelete));
ownerApi.post('/products/:id/content',validate(z.object({type:z.enum(['FILE','IMAGE','VIDEO','AUDIO','TEXT','LINK']),title:z.string().min(1).max(160),description:z.string().max(2000).optional(),text_content:z.string().max(50000).optional(),url:z.string().url().optional(),sort_order:z.coerce.number().int().min(0).max(10000).optional(),is_preview:z.boolean().optional(),access_type:z.enum(['PUBLIC','PREVIEW','PURCHASED']).optional()})),asyncHandler(api.ownerController.productContent));
ownerApi.delete('/products/:id/content/:contentId',asyncHandler(api.ownerController.productContentDelete));
ownerApi.post('/products/:id/upload',upload.single('file'),asyncHandler(api.ownerUpload));
ownerApi.get('/categories',asyncHandler(api.ownerController.categories));
ownerApi.post('/categories',asyncHandler(api.ownerController.categoryCreate));
ownerApi.put('/categories/:id',asyncHandler(api.ownerController.categoryUpdate));
ownerApi.get('/orders',asyncHandler(api.ownerController.orders));
ownerApi.post('/orders/:id/status',validate(z.object({status:z.enum(['PENDING','PAID','PROCESSING','COMPLETED','CANCELLED'])})),asyncHandler(api.ownerController.orderStatus));
ownerApi.get('/payments',asyncHandler(api.ownerController.payments));
ownerApi.get('/deposits',asyncHandler(api.ownerController.deposits));
ownerApi.get('/users',asyncHandler(api.ownerController.users));
ownerApi.get('/roles',asyncHandler(api.ownerController.roles));
ownerApi.post('/users/:id/ban',asyncHandler(api.ownerController.ban)); ownerApi.post('/users/:id/unban',asyncHandler(api.ownerController.unban)); ownerApi.post('/users/:id/suspend',asyncHandler(api.ownerController.suspend)); ownerApi.post('/users/:id/unsuspend',asyncHandler(api.ownerController.unsuspend)); ownerApi.post('/users/:id/change-role',validate(z.object({role:z.enum(['USER','MODERATOR','ADMIN','OWNER'])})),asyncHandler(api.ownerController.role)); ownerApi.post('/users/:id/reset-sessions',asyncHandler(api.ownerController.resetSessions)); ownerApi.delete('/users/:id',asyncHandler(api.ownerController.deleteUser));
ownerApi.get('/messages',asyncHandler(api.ownerController.messages)); ownerApi.post('/messages/:userId/reply',validate(z.object({body:z.string().min(1).max(10000)})),asyncHandler(api.ownerController.messageReply));
ownerApi.get('/tickets',asyncHandler(api.ownerController.tickets)); ownerApi.post('/tickets/:id/reply',asyncHandler(api.ownerController.ticketReply)); ownerApi.post('/tickets/:id/status',asyncHandler(api.ownerController.ticketStatus));
ownerApi.get('/services',asyncHandler(api.ownerController.services)); ownerApi.post('/services',asyncHandler(api.ownerController.serviceCreate)); ownerApi.put('/services/:id',asyncHandler(api.ownerController.serviceUpdate));
ownerApi.get('/settings',asyncHandler(api.ownerController.settings)); ownerApi.put('/settings',asyncHandler(api.ownerController.settingsSave)); ownerApi.get('/maintenance',asyncHandler(api.ownerController.maintenance)); ownerApi.put('/maintenance',asyncHandler(api.ownerController.maintenanceSave));
ownerApi.get('/storage',asyncHandler(api.ownerController.storage)); ownerApi.get('/system',asyncHandler(api.ownerController.system)); ownerApi.get('/login-history',asyncHandler(api.ownerController.loginHistory));
ownerApi.get('/activity',asyncHandler(api.ownerController.activity)); ownerApi.get('/reports',asyncHandler(api.ownerController.reports)); ownerApi.get('/security',asyncHandler(api.ownerController.security)); ownerApi.get('/faq',asyncHandler(api.ownerController.faq)); ownerApi.post('/faq',asyncHandler(api.ownerController.faqCreate)); ownerApi.put('/faq/:id',asyncHandler(api.ownerController.faqUpdate)); ownerApi.get('/information',asyncHandler(api.ownerController.information)); ownerApi.post('/information',asyncHandler(api.ownerController.informationCreate)); ownerApi.put('/information/:id',asyncHandler(api.ownerController.informationUpdate)); ownerApi.get('/notifications',asyncHandler(api.ownerController.notifications)); ownerApi.post('/notifications',validate(z.object({user_id:z.string().uuid().nullable().optional(),type:z.enum(['ORDER','PAYMENT','DEPOSIT','TICKET','SYSTEM','PROMOTION']),title:z.string().min(2).max(160),body:z.string().min(2).max(5000),link:z.string().max(500).nullable().optional()})),asyncHandler(api.ownerController.notificationCreate)); ownerApi.post('/notifications/broadcast',validate(z.object({type:z.enum(['SYSTEM','PROMOTION','ORDER','PAYMENT','DEPOSIT','TICKET']),title:z.string().min(2).max(160),body:z.string().min(2).max(5000),link:z.string().max(500).nullable().optional()})),asyncHandler(api.ownerController.notificationBroadcast)); ownerApi.get('/refunds',asyncHandler(api.ownerController.refunds)); ownerApi.post('/refunds/:id',validate(z.object({reason:z.string().min(5).max(500)})),asyncHandler(api.ownerController.refund));
apiRouter.use('/owner',ownerApi);

const webhookRouter=express.Router();
webhookRouter.post('/',express.raw({type:'application/json',limit:'1mb'}),asyncHandler(async(req,res)=>{const raw=req.body;const signature=req.headers['x-signature']||req.headers[loadEnv().PAYMENT_WEBHOOK_SIGNATURE_HEADER.toLowerCase()];let payload;try{payload=JSON.parse(raw.toString('utf8'))}catch{throw Object.assign(new Error('Invalid webhook JSON'),{status:400,code:'INVALID_WEBHOOK_JSON',expose:true})}const out=await require('../services/payment/payment.service').processWebhook(raw,signature,payload);return ok(res,out)}));

module.exports={apiRouter,pageRouter,webhookRouter};
