module.exports = {
  PRODUCT: ['DRAFT','PUBLISHED','ARCHIVED'],
  ORDER: ['PENDING','PAID','PROCESSING','COMPLETED','FAILED','CANCELLED','EXPIRED','REFUNDED'],
  PAYMENT: ['PENDING','PAID','FAILED','EXPIRED','REFUNDED','CANCELLED'],
  DEPOSIT: ['PENDING','SUCCESS','FAILED','EXPIRED','REFUNDED'],
  ACCOUNT: ['ACTIVE','SUSPENDED','BANNED','PENDING'],
  TICKET: ['OPEN','WAITING','REPLIED','CLOSED'],
  ENTITLEMENT: ['ACTIVE','REVOKED','EXPIRED'],
  CONTENT_TYPES: ['FILE','IMAGE','VIDEO','AUDIO','TEXT','LINK'],
  ACCESS_TYPES: ['PUBLIC','PREVIEW','PURCHASED']
};
